### ISSUE TITLE
retrieve a single record out of a store

### ISSUE THREAD

**Issue by svnlto** [spoike/refluxjs#119]
this might be trivial, but can you provide an example how to get a single object out of a store in the case of a simple master-detail view?

**Comment by alexciarlillo** [comment]
@iofjuupasli is that example complete? I'm not understanding where the .get() methods are coming from. i.e. currentPageStore.get().

@spoike To clarify I think what is meant by Master-Detail is, for example, having a list of Posts and wanting to get a hold of a single Post. Looking for similar information is what led me here. 

In my case I have a PostsList component, listening to a Posts store. This worked great to spit out a list of posts from a REST backend. Now I want to do something when the user clicks on a single Post: show some extra content under a new route and make it editable. So is there a "preferred" way of doing this? Should I create a Post (single) store and make another AJAX call to load the post... then we need to let to the Posts store know if any data was changed (we could listen to the same action, or listenTo the single Post store). Or grab the post directly from the Posts store (using a synchronous function) - this seems like an anti-pattern since we want all of our dealing with Stores to be done through actions, not directly calling methods from store, correct?

In general I think this pattern is new to a lot of us and we are struggling to wrap our heads around it and "do it right" rather than just do something that works. I can get this example to work in a few ways, but I don't grok all this enough to be sure I'm not coding myself into a corner with my solutions. I think that is part of where generic questions like this come from.

**Comment by iofjuupasli** [comment]
@alexciarlillo
get is shortcut for getDefauldData
Pay attention that in new version this method was renamed. 
Also, me example isn't FLUXy (as I understand it). But it works perfectly. Be careful to not duplicate data in stores.
I advise to store partials of Post in same array (same store) with complete posts. If necessary, you can add method on store to get data about completeness of posts. 
Don't worry about calling syncronic pure methods on store. But any change to store should be through actions. So fetch (note the difference between get and fetch) is something that calls API and update data in store.
