### ISSUE TITLE
Handling race conditions in reflux/flux

### ISSUE THREAD

**Issue by Chrisui** [spoike/refluxjs#122]
Imagine you have a hybrid web application with two screens next to each other which the user could swipe between. Each of these two pages has a collection of posts displayed for which the data is fetched async.

When you view the one page you fire an action, fetch the data, fire a complete action and update your `PostsStore`. When you slide to the other page the same happens again. Now imagine the second screen request was being slow, and so the user swipes back which loads the first page again. A few moments later the 2nd screen requests arrives back, fires the action, updates the store. So now you have updated your store with data from the screen on the other.

So one way you can solve this simple problem is have two stores. `ScreenOnePosts` and `ScreenTwoPosts`. And I guess you then have more actions or simply supply a property to your actions to tell it which variation of store you want to update when you call `actions.fetchPosts`.

That seems to work fine to begin with but then can get a bit unwieldly (at least it doesn't seem I've discovered the optimum structure). Imagine now you have 'groups' and in these groups you have a list of posts and the user can switch between groups. You see the same potential race condition arise again. In this case, because you don't know your groups ahead of time, you can't have multiple stores but the only way I can see is to send a property with the original action which flows down into the "fulfilled' actions to determine whether a `GroupPosts` store should be updated? In this case you would have to actively keep track of the 'current group' to determine whether you want to handle the `actions.fetchPostsSuccess` right?

I'm wondering if any of this makes sense to anyone? Pretty sure I'm overthinking things! Has anyone encountered these issues and have come up with or know a decent solution?

Thanks in advance for any help!

**Comment by tomconroy** [comment]
Perhaps you should just cancel the request when the user swipes away (or when you start a new request for the same action). With jQuery, you can just call `abort()` on the promise.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
