### ISSUE TITLE
Jasmine / SpyOn Issue

### ISSUE THREAD

**Issue by andyl** [spoike/refluxjs#139]
I can't get jasmine spies to work in a store that is subscribed to an action.  Here's some sample code:

```coffeescript
actions = Reflux.createActions ["actionOne"]
storeCreator = ->
  Reflux.createStore
    init: -> @listenTo(actions.actionOne, @onActionOne)
    onActionOne: -> console.log "I WAS CALLED"

describe "spyOn test", ->
  it "works when called directly", ->                           # test case 1 - works
    store = storeCreator()
    spyOn store, "onActionOne"
    store.onActionOne()
    expect(store.onActionOne).toHaveBeenCalled()
  it "fails when invoked via an action", ->                     # test case 2 - fails
    store = storeCreator()
    spyOn store, "onActionOne"
    actions.actionOne.trigger()  # synchronous call...
    expect(store.onActionOne).toHaveBeenCalled()
```
In both tests, I know that `onActionOne` has been called because I see the `console.log` message.

This problem happens with both Jasmine and Sinon spy tools.

Can anyone tell me if there is a way to make `spyOn` work in test case 2?  Or some other way that the test can show that the `onActionOne` function was called??

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
