### ISSUE TITLE
loading UI...

### ISSUE THREAD

**Issue by maxguzenski** [spoike/refluxjs#152]
Hi,
I'm porting a social network to react + flux (reflux) and I dont sure how handle a loading spin UI indicator. My first implementation is put "loading" as a model state, but it make React rerender everthing just to show the loading icon. 

For example, I have a search page, with a filter form, when user click on "search!" I want to make this button disabled and show a spin close to it.

```javascript
var Actions = Reflux.createActions(['searchUsers', 'searchUsersComplete']);

Actions.searchUsers.preEmit = function(params) {
  $.post('/searches.json', params, fucntion (data) { Actions.loadUsersComplete(data); }
};

var Store = Reflux.createStore({
  ...,
  onSearchUsers: function() { this.data.searching = true; this.trigger(this.data); }
  onLoadUsersComplete: function(data) { ... }
});

// components just re render everthing
```

Another idea is use Actions with promise (that I think is not supported by reflux), like that:

```javascript
// we will rerender just filter form
var SearchFilter = React.createClass({
  handleSubmit: function(params) {
    this.setState({loading: true});
    Actions.searchUsers(params).done(function() { this.setState({loading: false}); }
  }
});
```

At least, another idea is use a LoadingStore just for that, but this Store need to know what components executed action... 

So, Which you think that is the better way?

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
