### ISSUE TITLE
Structuring reflux apps

### ISSUE THREAD

**Issue by srph** [spoike/refluxjs#155]
I apologize for this useless issue, not anything about reflux. However, I'm confused with how I should structure my reflux app. For instance I have 5 crud modules, is this how it should be done? Fairly new to flux.

```
├── user/
|  ├── components/
|  ├── UserStore.js
|  ├── UserActions.js
├── user-create/
|  ├── components/
|  ├── UserStore.js
|  ├── UserCreateActions.js
```

One Store and Action for each [index, create].. per module (so that's around 15 store / actions), is that right?

Most structure of open-source reflux/flux projects I found weren't scaling for lots of modules or components.

**Comment by bluejamesbond** [comment]
@spoike How do you recommending managing actions / stores while considering the application will grow in time? At the moment, I am fairly new to Reflux since you have had more experience it would be great can provide your input.

**Comment by ivan-kleshnin** [comment]
@willembult I'm the fan of module based structure. 

> it typically becomes harder to maintain role-based organization (i.e. actions, stores, components as proposed above), as opposed to domain-based organization (e.g. Session, Products, Order)

100% true. Because your changes are way more often localized inside **module (model)** than **aspect**. At *hello-world* level it does not matter. But imagine we have 3 "business modules" within our project add we want to add new field for model and form. In "classic" aspect-based (models / controllers / views ) approach we'll need to open and close 3 * 3 folders which may be rendered far from each other in project file tree. In module base approach we'll need to open only 1 + 3 folders.

I actually experimented with different hierarchies a few months ago with timer and discovered that "classic" is nearly two times slower than "modular" in practice.

**Comment by spoike** [comment]
@bluejamesbond I'm usually splitting up stores when they become too large, which reflux allows you to do. I follow the "refactor mercilessly" principle, so this usually isn't an issue.

The notion that a store is _"one source of truth"_ is to me a bit problematic guidance since it implies you have to have just *one gigantic* store, which is the part of that guidance that I feverishly disagree with. Though the latest from facebook from the React conference about QueryML makes this strategy a bit more viable if you are able to keep that one store as generic as possible.

**Comment by ivan-kleshnin** [comment]
@spoike constant refactor is not a good sign on itself.

**Comment by spoike** [comment]
@ivan-kleshnin I believe it is a balance act that depends on value and time (like a lot of other things). I try to keep the refactorings tiny and that gives a lot of value for the sake of extensibility or maintainability. If a refactoring takes more than a day to perform, it is in my mind an indication of bad code architecture (or bad tooling but that usually isn't the case in my experience).

**Comment by vogrelord** [comment]
Another vital point here is reusability of features. 
Imagine we have a book reader component, that should be able to deal with some complex api - being able to gain chapters, content, quotes, etc.

That component will have a store file, actions file, dozen of component files, some Api class. 
And what if we need to reuse and maintain that component over five projects that our company develop? We almost certainly cannot splatter all these files across the project.

Another point of concern here is using Singletons, but it's a whole different story.

**Comment by srph** [comment]
I was still misunderstanding Flux the time this was written. I am closing this. So far, I have

```
|-- actions
|-- components
|-- handlers
|-- stores
|-- utils
|-- index.js
|-- config.js
|-- routes.js
```
