### ISSUE TITLE
Handling errors in save, update, etc?

### ISSUE THREAD

**Issue by drewhamlett** [spoike/refluxjs#162]
I don't want to mix display logic with the store so what if I wanted to display an error on save failure.  Right now I'm doing this, which seems wrong.

```js
onAddProduct: function (product) {
       var self = this;
        request
            .post('/api/products.json')
            .send(product)
            .set('Accept', 'application/json')
            .end(function(error, res) {
                if (res.status === 200) {
                    toastr.success('Product created successfully!');                  
                    self.trigger(self._group);
                    return;
                }
                toastr.error('Error creating product');
            });
}
```

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
