### ISSUE TITLE
Question: destructor method in Store

### ISSUE THREAD

**Issue by mschipperheyn** [spoike/refluxjs#179]
Is there a destructor method in Store, the counter part of init, in case you need to do cleanup of certain things?

**Comment by srph** [comment]
You can unsubscribe to listeners, I think. AFAICR,  ```subscribe``` fn returns an ```unsubscribe``` fn.

**Comment by mschipperheyn** [comment]
Yeah, but I need to be able to call that unsubscribe on destruction of the Store. For which you would need a destructor. Kind of like componentWillUnmount. Perhaps my YUI past makes me too focussed on this stuff. In that framework, any handlers that didn't get cleaned up, ended up creating trouble in one page style applications.

**Comment by gpbl** [comment]
@mschipperheyn just curious, in which case do you need to destroy the store? in this `require` world, once it is in memory, you shouldn't need to unload a module. Anyway the task should be managed by your module loader (for example, [with webpack](https://github.com/webpack/webpack/issues/156)).
(+1 for coming from the yui world :)

**Comment by mschipperheyn** [comment]
@gpbl you might be right. But the idea that you don't have to worry about cleanup just doesn't sit well with me. I don't have the experience w this framework yet though to judge if problems could pop up

**Comment by gpbl** [comment]
Wait, are you talking about a store *data* or a store itself? I consider that all my modules, and stores as well, may end up in the browser (or node) memory - that is, the whole application. Destroying them for reinitializing them once they are needed again doesn't sound right (infact on node would sound like an hack). 
Another case is for stored data: if you have MB of data then, yes, I'd consider to delete them when not needed (and let the garbage collector free the memory). But I see this as an edge case and more critical on the server then the browser.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
