### ISSUE TITLE
About caching and reusing data in stores

### ISSUE THREAD

**Issue by gpbl** [spoike/refluxjs#180]
Now that v0.2.2 provides a nicer API for loading asynchronous data, I want to place my API requests in `actions`. Yet I'm not sure how to reuse data already cached in the stores. 

(I'm sorry if you have already discussed this thing before, maybe I've lost the discussion somewhere. Also, I miss a gitter chat :-)

Before, i had my stores managing this:

```js
// store listening to `load` action
onLoad() {
   if (this.getData()) 
     // use cached data    
     this.trigger(this.getData())
   else 
     // async bunga bunga
}
```
I was tempted to do something like this:

```js
// actions
myActions.load.listen(() => {
    if (myStore.getData()) 
       // use cached data
       myActions.load.completed(myStore.getData())
    else 
      // start async operation ...
});
```

but this won't work, since `actions` is required from `store` as well, causing a circular dependency.

I solved putting the logic in the component:

```js
// mycomponent.jsx

componentDidMount() {
   if (store.getData()) 
      // reuse cache
      this.setState({data: getData()})
   else
      // async action
      actions.loadData()  
}
```

I prefer this approach because:
– a possible `loading` state is managed from the component and not the store
– my `getData()` function could receive an argument with the fields I need from my data (in case of the data is available but incomplete)

Does this sound right or have you found a better approach?

**Comment by gpbl** [comment]
I've tried to put my reasonings in [this gist](https://gist.github.com/gpbl/ec05807f84b2fc8a970d). The case is related to *Combine results React getInitialState and Reflux getInitialState* https://github.com/spoike/refluxjs/issues/166 and may be a case for server-rendering https://github.com/spoike/refluxjs/issues/144? (I know @appsforartists has made progress but i'm still some steps behind :-) )

**Comment by simonsmith** [comment]
@gpbl I use sessionStorage on this small app - https://github.com/simonsmith/github-user-search

I decided to allow the actions to read from the cache and let the stores save to the cache. When calling the the `this.completed` method from the action I pass along whether it was from the cache or not, then the stores know whether to do something with the data.

Hope that helps

**Comment by damassi** [comment]
I'm quite curious about the preferred approach here as well.

**Comment by ivan-kleshnin** [comment]
I personally think, that only store should be concerned with data retrieval.
Check it's state, nope, check localStorage, nope then raise ajax request.
Than approach when you move data-related stuff to actions or scatter cache setters and getters through application parts smells bad to me.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
