### ISSUE TITLE
Where to get help?

### ISSUE THREAD

**Issue by emacsen** [spoike/refluxjs#189]
I'm having a problem with a React component and the connect mixin. It never seems to store the state of the store in my statekey. Normally I'd go on a mailing list or IRC to see what I'm doing wrong.

Where is the right forum for in regards to reflux?

Maybe update the README with it?

**Comment by gabro** [comment]
I guess Stackoveflow could be appropriate

**Comment by jrm2k6** [comment]
I think an irc channel on Freenode would be awesome.

**Comment by srph** [comment]
Or gitter? :smiley_cat:

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)

**Comment by spoike** [comment]
This is in the README btw.
