### ISSUE TITLE
Global state

### ISSUE THREAD

**Issue by bjornua** [spoike/refluxjs#191]
I am trying to figure out how to use this library server-side, and I could use some pointers.

The current challenge is handling global state in refluxjs. I don't want to share state between requests.

Currently my strategy is to recreate the stores between every request to make sure no state is shared. 

But then I noticed that the stores are pushed in keep.js making the array in keep.js grow larger. So that means that I have to reset the store between request.

Am I missing something, or is this the right way to go about this?

**Comment by spoike** [comment]
You can find some tips at #144, haven't gone through it all yet, but the general concensus is to rehydrate the stores instead of creating stores (since reflux keep track of all created stores). Someone wrote a mixin that does this data hydration automatically but I can't find it at this moment.

**Comment by gpbl** [comment]
In my experience trying to make reflux working server-side makes the app rather complex, and I considered to keep reflux out of the server-side. 

Anyway, you would need to rehydrate the stores on the client (with a [simple mixin](https://github.com/spoike/refluxjs/pull/124#issuecomment-69107578)). Stores must have a unique name. To dehydrate you can use the good `serialize-javascript` npm module.

**Comment by influx6** [comment]
@gpbl I agree and understand that reflux is coded to be client only, the key is simply having a means of getting the data from server to client and still be able to support search engines as needed if it's part of the plans.

**Comment by influx6** [comment]
@gpbl  As stated there are means of rehydration the stores from server to client and that is the best option forgetting the search engines, and in fact their always alternatives to sever side rendering, let reflux stick to rehydration and dehydration and let a custom rendering system be made to deal with search engines and the likes

**Comment by influx6** [comment]
As to the question and problem @bjornua ,i would advice the rehydration route, creating and tearing down stores means more cup work and as you say isn't memory efficient, look to #144 for a detail on the hydration solution

**Comment by gpbl** [comment]
In my exploration on the subject I went up to server-side rendering, keeping reflux working client side. 

Your route handler component can pass the stores state (that to be dehydrated) as prop:

```js
// server side 
const markup = React.renderToString(<Handler storesState={storesState} {...i18n} />);
// now send markup with dehydrated state as response
```

The Handler would use a mixin to consume the `storesState` prop when rendered server side, or the store's `initialState` when it has been rehydrated on the client:

```js
// StoresStateMixin.js
export default {
  getStoreInitialState(store) {
    if (env.SERVER && this.props.storeState && this.props.storeState[store.name])
        return this.props.storeState[name];
    else
      return store.getInitialState();
  }
};
// route handler example
const MyRouteHandler = React.createClass({
  mixins: [StoresStateMixin],

  getInitialState() {
    const state = this.getStoreInitialState(myStore);
    return state
  },
  // ...
```

**Comment by schutterp** [comment]
@gpbl what about avoiding Reflux.createActions calls on the serverside?

In my project, the top-level component acts as the controller, thus it depends on the stores (using a Reflux.connect mixin for each store). Reflux.createStore is called when the store module is `require`d (which you seem to suggest I should avoid using mixins). But then, some of the child components are dependent on the actions because they call them directly per the flux pattern.

I think what you're saying is that I need the added complexity to avoid any Reflux.create* calls on the server?

**Comment by gpbl** [comment]
> what about avoiding Reflux.createActions calls on the serverside?

@schutterp what would you do instead? I'm not sure I understand how you create stores/actions.

> Some of the child components are dependent on the actions because they call them directly per the flux pattern.

Are the actions called on `componentWill/DidMount`? Because in this case there's no way for the server to render the components again. Before your controller-component is rendered, the actions must be already completed, with your stores ready and filled up with data. In fact, it would help if actions could stay out of the component's lifecycle... 

(keep in mind these are just experiments)
