### ISSUE TITLE
Handling state is a disaster

### ISSUE THREAD

**Issue by ivan-kleshnin** [spoike/refluxjs#197]
In React components what is returned from `getInitialState` becoming... `this.state`.
But in Reflux stores, **developer** have to mess with this *manually* like this:

```javascript
let Component = React.createClass({
  ...
  getInitialState() {
    return {};    
  }
});

let store = Reflux.createStore({
  ...
  getInitialState() {
    this.state = whatever;
    return this.state;
  }
});
```

So we renamed that `getDefaultData` to `getInitialState` but it behaves totally different from what component does... I find this utmost confusing and it looks really hacky. Yes, store instance is a singleton and component is a class, it's *kinda* explainable, but still utmost confusing.

I spent many hours googling how people handle state (with reflux, particularly) and it was a great disappointment to discover that noone seems to discover a decent solution yet. Someone recommends to keep app state in components and calls it... Flux (despite that Flux documentation says quite the opposite). I wonder if *stateless* store may be called store at all... Someone recommends to wire components to store and init data in `store.getInitialState`. Others create initial state in `store.init`. And others [create global variable to keep state there](http://www.sitepoint.com/creating-note-taking-app-react-flux/) I also saw people just duplicate `getInitialState` calls with the same keys in components and stores (e.g. they do things without any understanding whats going on, just hack around until "works"). 

This is a real disaster, to be honest. Please prove I'm wrong. I want to be wrong. 
I predict this year will be spent in architecture wars over React.

**Comment by spoike** [comment]
I agree, it's been a hack so far. Reason behind the naming of the `getInitialState` method (IIRC #117) is that Reflux will be automatically feeding the component with a mixin from that method and it seemed like a good idea at the time to name it the same.

There has been some discussion about having easier state handling in a store e.g. #174, which will benefit making a React app isomorphic (#144) since it will make dehydration/hydration of data easier as well. I agree that rationale behind store instance as a singleton makes sense client-side but not server-side.

**Comment by ivan-kleshnin** [comment]
@spoike I don't even approached to isomorphic apps yet :( 
I've read through **all** reflux issues today trying to wrap my head around all this. 
Still without much luck. I really like the ideas you've put behind reflux, though my brain is yet unable to absorb the whole picture.

**Comment by LongLiveCHIEF** [comment]
Adding to roadmap.
