### ISSUE TITLE
[question] Structure of parent/child relationship

### ISSUE THREAD

**Issue by danawoodman** [spoike/refluxjs#198]
This is a general architecture when using Reflux to store collections of data. In Backbone, one has Collection and Model which makes structuring listing/detail views relatively straightforward. 

I'm searching for good way to accomplish the same in reflux. I'm wondering if there is a standard idiom for this that others are using. Specifically I'm interested in how this works along side a router like [react-router](https://github.com/rackt/react-router/).

I can think of a few ways to do it:

- Have a `ProductsStore` and then a `ProductStore` that fetches a given project via API/WebSockets/whatever.
- Add a method to `ProductsStore` to return a single product.
- Something else I'm not thinking of...

Maybe some can shed light on how you architect a parent/child relationship with Reflux?

**Comment by Cethy** [comment]
[this post](https://github.com/gaearon/flux-react-router-example#how-i-classify-stores) might help you (as it helped me) structure your stores.
Basically, you should not duplicate data informations, and use one "singleton" data store (for each type of data you have) and several "selection/idList" store, even for one entity, which listen to the data store (in case the entity is deleted or else).

Also I tends to think my selectStore as per features, for example I have a feature "paginated list of object" and a feature "details of one object" ; therefore, I will have one dataStore which will store all my objects data, one selectStore which will hold the ids currently displayed in the list (+ the current page, ...) & one "detailsStore" which will hold the id of the object displayed on my details page (+ eventual other states of this page).


As per the way to populate components with the actual data, I use a `dataStore.getAll()` & a `dataStore.getOne(id)` methods when I receive the id (or ids) from the selectStores.
Since the selectStore is not allowed to hold a not existing id (since it listen to dataStore), it works well. But i'm sure the process could use some improvements.

**Comment by danawoodman** [comment]
Thanks @Cethy, this is helpful. I'll play around with that example code and find a way to integrate the concepts into my project.

**Comment by ivan-kleshnin** [comment]
> Also I tends to think my selectStore as per features, for example I have a feature "paginated list of object" and a feature "details of one object" ; therefore, I will have one dataStore which will store all my objects data, one selectStore which will hold the ids currently displayed in the list (+ the current page, ...) & one "detailsStore" which will hold the id of the object displayed on my details page (+ eventual other states of this page).

Why make a store to keep id, when that id should be in URL either it's REST or non REST?

**Comment by Cethy** [comment]
@ivan-kleshnin id in URL is an "app design" choice IMHO.
When I say "page", it's a wide term for an actual page, a panel, a popup or whatever you choose to display the details.

Also, I failed to mention that I don't use component state in stand-alone (always linked to a store), in order to get my app back exactly how I left it. This way, even a hide/show panel in the "details page" must be tracked in a store. And it's not the role of the listStore.

Does it answer your question ?

**Comment by ivan-kleshnin** [comment]
@Cethy thanks, it's clear answer and agree with your point.

**Comment by danawoodman** [comment]
Like this discussion. Anyone care to post a really simple hello world example with a list/detail view of a collection of objects? 


Also, when directly viewing a detail page, does the page set the current ID in the `detailStore` and then calls a function on the `listStore` to actually fetch the item from the API? How does the detailStore know when to update? Is it getting info about the item from the listStore? How does it know when the details change for the item?


Dana Woodman • danawoodman.com

**Comment by Cethy** [comment]
I'll try to spawn a simple app using this architecture, as it's kinda obscure and I would love to have feedback from more senior (reflux) devs.


>  How does the detailStore know when to update? Is it getting info about the item from the listStore? How does it know when the details change for the item?

To be sure we're talking about the same thing, when you say `listStore`, you mean `dataStore`, right ?
In this case, as I said in my first comment, your `detailsStore` should listen to `dataStore`, and `trigger` a new state (with basically the same info, we don't care) to force the `detailsComponent` to update the data it displays via `dataStore.getOne(id)`. 
You could set `detailsComponent`to listen directly to `dataStore`but it might disrupt some actions `detailsStore` could do before triggering the updated data.

> Also, when directly viewing a detail page, does the page set the current ID in the `detailStore` and then calls a function on the `listStore` to actually fetch the item from the API?

I didn't think about that, since my apps are always "one-page apps" and there is some kind of initialization going on behind the scene loading the `dataStore`.
IMHO, if you just display a `detailsPage` and don't want to ask the API for the all collection, you should initialize an empty `dataStore` and add a failsafe in the `dataStore.getOne(id)` method which will ask the API if its collection is not initialized.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
