### ISSUE TITLE
Understanding action children

### ISSUE THREAD

**Issue by powmedia** [spoike/refluxjs#204]
I'm trying to establish a simple way of dealing with actions in the case where I'm creating a complex form.    I've read recommendations on creating separate error stores, multiple types of actions etc but it feels overly complex for such a simple (and common) scenario.

Once the user submits the form, there will be server side validation which could return an object detailing the errors in the form. These should be applied, highlighting fields that failed tests, with error messages etc.  In pseudo code this is what I'm thinking at the moment:

```
var registerAction = Reflux.createAction({ children: ['completed', 'failed'] });

var Store = Reflux.createStore({
  mixins: [Reflux.listenTo(registerAction, 'onRegister')],

  onRegister: function(data) {
    myAPI.register(data, function(err, res) {
      if (err) return registerAction.failed(err);
 
      registerAction.completed(res);
    });
  }
});

var RegisterForm = React.createClass({
  render: {...},

  mixins: [
    Reflux.listenTo(registerAction.failed, 'onError'),
    Reflux.listenTo(registerAction.completed, 'onSuccess')
  ],

  onSubmit: function() {
    registerAction(this.getFormData());
  },

  onError: function(err) { //Show errors and feedback in form },
  onSuccess: function(res) { //OK, close form }
});
```

Does this seem like a good approach or would I be better off using preEmit() or another method?  Any advice welcome, I just didn't see much in the docs about how to actually use action children etc.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
