### ISSUE TITLE
Does the listenables shorthand handle child actions?

### ISSUE THREAD

**Issue by epeli** [spoike/refluxjs#213]
if I do 

```js
var Actions = Reflux.createActions({
  bang: {children: ["completed","failed"]},
})
```

and in a store I set `listenables: Actions` do I get callbacks automatically for the `completed` and `failed`actions like `onBang`for the `bang` action?

**Comment by uniphil** [comment]
I ran into exactly this yesterday. The answer is: yes!

```javascript
var noiseStore = Reflux.createStore({
  listenables: Actions
  onBang: function() { this.trigger('bang started...'); },
  onBangCompleted: function() { this.trigger('bang worked!'); },
  onBangFailed: function() { this.trigger('bang backfired :('); }
});
```

**Comment by epeli** [comment]
Thanks! I believe this is not documented.

**Comment by gabro** [comment]
It's documented, although "implicitly":

From the [Listening to many actions at once](https://github.com/spoike/refluxjs#listening-to-many-actions-at-once) paragraph
> This will add listeners to all actions `actionName` who have a corresponding `onActionName` (or `actionName` if you prefer) method in the store.

So, given that children actions are just actions after all, listeners will be automatically created for them too.

**Comment by aesopwolf** [comment]
Does the convenience mixin ```mixins: [Reflux.listenTo(Actions, "foobarActionSubscriber")]``` shorthand work with this? I'm not sure if I'm doing something wrong, or if it's simply not supported. Help! :)

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
