### ISSUE TITLE
Handling one store with multiple different objects

### ISSUE THREAD

**Issue by OAGr** [spoike/refluxjs#217]
In the [Facebook Chat example](https://github.com/facebook/flux/blob/master/examples/flux-chat/js/stores/ThreadStore.js), they use one store (the thread store) to handle both the list of the _threads and the _currentID of the current thread.

I'm trying to do a similar thing with Reflux.  On the whole it seems possible, except that stores seem to include a getInitialState method with only one return value.  

```
var exampleStore = Reflux.createStore({
    init: function() {},
    getInitialState: function() {
        return "the initial data";
    }
});
```

I like the [Issue 174](https://github.com/spoike/refluxjs/issues/174) improvement, which would solve this, essentially by making this return value a hash.  However, in the mean time,
  
1.  Is there any way to get getInitialState to return multiple arguments?
2.  Would it be recommended to split up _threads and _currentID in a reflux application?

**Comment by confiks** [comment]
I don't see why you need proposal #174 to make Reflux emit a hash / object / multiple values. You decide what to emit entirely yourself with Reflux. Just set `this.state = {}` at store init, update the hash as you wish, and `trigger(this.state)` on every action.

Although I use setState with Reflux myself, I don't really like to have proposal #174 integrated in Reflux, because I think people are trying to cram way too much in what should be a leaner Flux library. With mixins, you can easily create the pattern yourself.

As for your second question: if you are managing a collection and a single resource, I think you should just maintain two stores. Different components will listen to those stores, and they handle different concerns.

**Comment by OAGr** [comment]
I ended up going with a separate store, and it's been working out so far.  Thanks!
