### ISSUE TITLE
Writing tests for RefluxJS

### ISSUE THREAD

**Issue by srph** [spoike/refluxjs#254]
> I'm confused on testing RefluxJS. In my case, given that I have MessageStore and ActionStore, and the Store only listens to the Action, and no other store listens to the Action. Do I test the both the Action and Stores together or separately?
> 
> Might be an insignificant information, but I am using Jest.

This is a [question](http://stackoverflow.com/questions/28644002/writing-tests-for-refluxjs) originally posted at SO.

**Comment by spoike** [comment]
Unless you're doing some `preEmit` stuff on actions, it's kind of pointless to test them since all they do is pass on the arguments to anything listening on the action. There is little chance of regression and Reflux test suite should take care of that part.

It's more useful to test the stores and that they handle action invocations and other dependencies correctly (i.e. trigger with correct output).

**Comment by srph** [comment]
Alright, thanks. By the way, this may sound stupid and obvious, but I am using Jest (```facebook/jest```) which ```mocks```s all dependencies (fetched with ```require()```). Should I ```unmock``` the actions which the stores listen to?

**Comment by jankuca** [comment]
Unless you mock them on your own, you should deny Jest from mocking them.

**Comment by srph** [comment]
Thanks @spoike and @jankuca :bow:
