### ISSUE TITLE
How the typical async resource load should looks like?

### ISSUE THREAD

**Issue by michaltaberski** [spoike/refluxjs#297]
Hi, 

I went through the reflux documentation, and todo code. However I could not find how the pattern for async resource fetching would looks like?

Imagine I have `$.get('/list.json', ...)`

and I would like to have simple list or table and loading state (eg spiner).

Where we should call data fetching? On preEmit, inside datastore? Is the datastore a proper place to keep information that resource was loaded?

**Comment by WRidder** [comment]
In my case I used actions for async loading. Which means an action will trigger an async load and once done, trigger other actions to which stores are listening. 

For an example, see: https://github.com/WRidder/react-spa/blob/master/client/src/actions/resourceActions.js

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
