### ISSUE TITLE
Undefined actions silently fail

### ISSUE THREAD

**Issue by zeen** [spoike/refluxjs#301]
Ran into an issue with camel-casing. Here's some sample code extracted from my app:

```js
var Actions = Reflux.createActions(["minimize", "unminimize"]);
var Store = Reflux.createStore({
    listenables: Actions,
    onMinimize: function() { console.log("Minimized!"); },
    onUnMinimize: function(){ console.log("Restored!"); }
});
Actions.minimize(); // Logs "Minimized!"
Actions.unminimize(); // Doesn't log anything, silently fails
```
The silent failure is because the store has `onUnMinimize`, and not `onUnminimize`.

The main thing that bothers me is the silent nature of the failure. I'd expect an exception or at least a `console.warn` when an action causes nothing to be triggered. Preferably an error while creating the store, but I assume that's not practical.

**Comment by xgrommx** [comment]
Hi @zeen I think this problem could be solved if you will use 
```js
var Actions = Reflux.createActions(["minimize", "unMinimize"]);
```
instead of
```js
var Actions = Reflux.createActions(["minimize", "unminimize"]);
```

And in your actions should be triggered like this

```js
...
Actions.unMinimize();
```

Maybe it's happened because you need use camelcase syntax. In javascript convention should be camelcase. I hope that I helped you. Enjoy

**Comment by akre54** [comment]
It's definitely an issue of casing, but I believe @zeen's point is that actions shouldn't silently fail when there are no listeners to receive them. This is a tricky one, since actions are more analogous to triggering an event on an event emitter (which is silent for nonexistent events) than calling a method on an object (which complains with a TypeError for nonexistent methods).

Unlike triggering an event, however, an action should almost always do something. I certainly can't think of a case where you would want to call an action that *doesn't* do anything. Having Reflux complain when there are no listeners of that action may make sense.

**Comment by tmbtech** [comment]
We avoid this by creating objects with Reflux.createAction(). This should also help with autocomplete (if you are using an IDE)


```
import Reflux from "reflux";

var PromisesActions = {
    runWaterfall: Reflux.createAction(),
    runInParallel: Reflux.createAction(),
    clearMessages: Reflux.createAction()
};

export default PromisesActions;
```

**Comment by akre54** [comment]
@tmbtech this has the same problems as `createActions`. It doesn't fix anything about the store or the triggering process, right?

**Comment by tmbtech** [comment]
right, we are mainly avoiding the problem.

**Comment by zeen** [comment]
@tmbtech Are you still not one typo away from silent failure? Example:

```
var PromisesActions = {
    runWaterfall: Reflux.createAction(),
    runInParallel: Reflux.createAction(),
    clearMessages: Reflux.createAction()
};
var Store = Reflux.createStore({
    listenables: PromisesActions,
    // note WaterFall vs Waterfall:
    runWaterFall: function() { console.log("runWaterFall!"); },
    runInParallel: function(){ console.log("runInParallel!"); }
    clearMessages: function(){ console.log("clearMessages!"); }
});
```

What I'd like on emitting the under-the-hood `EventEmitter` event is to throw an error if `listeners.length == 0` for that event.

**Comment by tmbtech** [comment]
@zeen, 

Yes that true. We actually try to avoid all convenience methods as a workaround.  Its a little more boilerplate code, but it's more declarative, less handwavy, and our linters/autocomplete help avoid the issue.

but again, I'm all for fixing the underlying problem instead of just avoidance. 

```
var PromisesActions = {
    runWaterfall: Reflux.createAction(),
    runInParallel: Reflux.createAction(),
    clearMessages: Reflux.createAction()
};
var Store = Reflux.createStore({
    init() {
        this.listenTo(PromisesActions.runWaterfall, this.onRunWaterfall);
        this.listenTo(PromisesActions.runInParallel, this.onRunInParallel);
        this.listenTo(PromisesActions.clearMessages, this.onClearMessages);
    },
     ....
});
```

**Comment by LongLiveCHIEF** [comment]
It is conceivable that a store would listen to a set of actions, but not handle all of them. However, as a few have pointed out, the underlying issue is the attempted invocation of an undeclared or undefined action, which shouldn't silently fail.

**Comment by LongLiveCHIEF** [comment]
I've thought a lot about this, and it's definitely conceivable, and *required*, for actions to silently fail if no listeners are set up to receive them.  There are a multitude of reasons for this, especially if you're following the Functional Reactive Programming approach.

As a good example:

an application may asynchronously create a store, or even the action handlers on a store (say for example, a store is decorated because of a new part of the app spinning up), long after the created action has been emitted many times. 

Now let's say that in your app, you want the user to be able to enable "desktop alerts".  After getting permission from the user to utilize this part of the application, the app might asynchronously stand up an `alertsStore`.  The actions that the `alertsStore` handle would have been firing all along, from other components in the application that the user would be able to turn on alerts for.
