### ISSUE TITLE
Individual store data for server side sessions

### ISSUE THREAD

**Issue by henit** [spoike/refluxjs#307]
Is there currently any way to use Reflux stores/actions server side (node+express) and have individual data in the stores per session user? Using the same store code, but the data in the store is individual per session?

The use case is a React frontend app (also using Reflux), different users connect to the backend api, and in the express routes, the users need to work on their own data in the stores.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
