### ISSUE TITLE
Handling multiple data sources on initial load

### ISSUE THREAD

**Issue by viperfx** [spoike/refluxjs#318]
Hi all, 

I am wondering what the best practise in reflux is when you have the following scenario: 
- Load multiple data sources (API) through an async request 
- Store the data as it comes in to the store
- Once all the requests have finished then load the component.

The way I am currently handling this to collect all the information from multiple sources on one end point on the server side. Its easy to handle a default state when there is just one data source. I would like to know what the recommended way of dealing with this without creating an endpoint for aggregation - as in handle it client side. If you could provide a simple example, that would be great too.

Thanks

**Comment by max-zelinski** [comment]
I've faced exactly the same problem.

The way I'm currently dealing with it is by deviating from the standard approach 'all changes must go through actions' and implementing store *get* methods with promises. This approach is mentioned in this excellent [interview](http://ianobermiller.com/blog/2014/09/15/react-and-flux-interview/) of one of facebook engineers.

On the components side I use ```react-async```/```react-transmit```. Those libraries add a wrapper on top of component that waits for store promises to be fulfilled and only then calls component ```render``` method.

Here is a sample [store](https://github.com/max-zelinski/spa-prototype/blob/promises-react-transmit/react-reflux-router/js/stores/paymentsStore.js) that I implemented with this approach and accompanying [controller](https://github.com/max-zelinski/spa-prototype/blob/promises-react-transmit/react-reflux-router/js/widgets/paymentsWidget.jsx) built with ```react-transmit``` or another variation of the [controller](https://github.com/max-zelinski/spa-prototype/blob/promises-react-async/react-reflux-router/js/widgets/paymentsWidget.jsx) built with ```react-async```

Personally I like ```react-transmit``` more implementation.

**Comment by LongLiveCHIEF** [comment]
There are countless ways you can achieve this, and how you do so depends on your application. There are examples in the readme that discuss the how to listen to actions, and then how to fire those actions when your app starts. Specifically, the [Asynchronous actions as Promises](https://github.com/spoike/refluxjs#asynchronous-actions-as-promises) section walks through this.

Since reflux is asynchronous to the core, each part of the reflux model (actions, stores), should best be implemented by by being setup to listen and wait... leaving how you wish to trigger the chain of events that they listen to up to you.

As a simpler alternative, you could make an asynchronous request to a data api directly within the stores `init` method.

```js
// uses superagent, `npm install superagent`
var store = Reflux.createStore({
  data: {stuff: []},

  init() {
    request("https://some/data/url.json", res => {
      this.data.stuff = JSON.parse(res.text);
      this.trigger(this.data);
    })
  },

  getInitialState() {
    return this.data;
  }
});
```

if you want, you can also use the [Reflux.storeMethods](https://github.com/spoike/refluxjs#refluxstoremethods) to add a method to every store that would handle registration and execution of data sourcesl

You should also consider your domain model, and consider if it's appropriate to use an aggregate store.
