### ISSUE TITLE
Using Reflux without mixins [question, usage]

### ISSUE THREAD

**Issue by markthethomas** [spoike/refluxjs#320]
What's the best way to go about using things like `connect` and some of the other mixins in a non-mixin manner? As I understand it, the react team is moving away from mixins in the future and I'm hoping not to rely on them too deeply.

**Comment by LongLiveCHIEF** [comment]
Reflux doesn't depend on React. Mixins used in reflux won't break if React removes mixin support. Reflux provides Actions and Stores, and let's you provide your own "component" implementation.  The mixins provided are just convenience methods available, that use the existing React component lifecycle.

For example of connecting to stores within a React component using the lifecycle directly (instead of via the mixin), [check out this example from the README.md](https://github.com/spoike/refluxjs#react-component-example)

**Comment by markthethomas** [comment]
Sorry, you're correct. Was confused by some of the documentation at the time; are there plans to clean that up or better unify it? If there are or there aren't, I'm happy to help/get that started. Thanks!

**Comment by LongLiveCHIEF** [comment]
Are you referring to the "[Mixins in stores]" section? Any thoughts on what could be improved?

**Comment by markthethomas** [comment]
Yeah, but maybe just more overall. Maybe it was just my being really new to flux and react, but I find some of the overalls organization a little confusing. I'll put some more structured thoughts together on it.

**Comment by LongLiveCHIEF** [comment]
It is a fair departure from the typical flux implementation, and is designed to be a [reactive](http://www.reactivemanifesto.org) approach to the flux paradigm. 

Having a good understanding of reactive programming will make things go down a bit easier i think. The FRP style is a key part of how stores and actions make themselves observable, which is what decouples Reflux from React. 

Facebook's Flux library is also independent of React, as it can be used as a architecture design pattern or framework for any front end library, but Flux uses a more immutable/isomorphic approach to achieve cohesion w/Flux -> React.
