### ISSUE TITLE
How about changing the function name 'listen' to 'register' in stores and actions?

### ISSUE THREAD

**Issue by howtomakeaturn** [spoike/refluxjs#328]
In React components we write

    componentDidMount: function(){
        gemStore.listen(this.onGemChange);    
    },

It looks like the store is listening to something. But actually it's the component listening to the store.

This may look better?

    componentDidMount: function(){
        gemStore.register(this.onGemChange);    
    },

In Reflux actions we write

    toggleGem.listen(function() {  
      isGemActivated = !isGemActivated;
      var strActivated = isGemActivated ? 
        'activated' : 
        'deactivated';
      console.log('Gem is ' + strActivated);
    });

It looks like action is listening to something. But actually it's just something we register to execute later.

This may look better?

    toggleGem.register(function() {  
      isGemActivated = !isGemActivated;
      var strActivated = isGemActivated ? 
        'activated' : 
        'deactivated';
      console.log('Gem is ' + strActivated);
    });

How do you guys think?

Thanks for any feedback.

**Comment by kevinsimper** [comment]
I think the benefit of using `listen` is that it is the same interface for actions, but I myself got confused when I thought I was listening to only a part of the store, but then found out it is actually the whole store, so my code always looks like this

```
this.unsubscribe = Store.listen(this.onChange
```

**Comment by LongLiveCHIEF** [comment]
Howdy!

I think you have a few things to sort out yet about how actions, stores, and components work, and what the responsibility is for each. The `listen` functions are appropriate because components listen to stores, and stores listen to actions.

I think `register` gives the idea that a component is responsible for creating an action, when in fact the component is listening for changes emitted by the store(s). Your stores should have handlers for the actions it listens to, and reflux makes this easy by shortcutting the name of the action, and automatically handling it if you use the `onActionName` syntax.

In turn, stores also listen to actions, so `listenables` is also appropriate there.  You could take a look at `mixins: [Reflux.connect(store)]`, as that might suit your needs, however, I think you're approaching the problem from the wrong direction.

In Reflux, and also in React, data flows down from the top. Your sample code has concerns from both the action and the store in it, and you should be separating out that logic, so that your store handles setting the state when an action it listens to is emitted.

At that point, your component will use the state passed to it from the store.  In a reflux/react implementation, you won't often find the keyword `is` being used, at least when it comes to state.ds

In your example, you'd want to do something like this:

```js
//create your action
var actions = Reflux.createActions({
    // see https://github.com/spoike/refluxjs#listenables-and-asynchronous-actions
    "toggleGem": {"active","inactive" }
});

// your store
var gemStore = Reflux.createStore({
    listenables: [actions],

    // toggleGem can be handled by prepending 'on' and using upper-camel-case for your action name
    onToggleGem: function(){
        // flip your state
    },

    // set your default states here for your components to use
    getInitialState: function(){
         return this.gems
    }
});

// your component
var gem = React.createClass({
    mixins: [Reflux.connect(store)],
    render: function(){
       // this.state.gems is available for use here due to the mixin
    }

});

**Comment by howtomakeaturn** [comment]
@LongLiveCHIEF @kevinsimper Thank you for the feedback!
I think I need to study more on this topic.
Thank you very much!
