### ISSUE TITLE
Store/Action Circular references

### ISSUE THREAD

**Issue by brianlawasdf123** [spoike/refluxjs#346]
From what I've read about flux, actions should be able to access stores in a read-only capacity. However in Reflux, since stores must reference the action instance for listening, this causes circular references. The following is an example of an ajax authentication scenario:

```
// profileStore.js
var profileActions = require('./profileActions);
var profileStore = Reflux.createStore({

    init: function () {
        this.listenToMany(profileActions);
    },
...
```

```
// profileActions.js
var profileStore = require('./profileStore');
...
actions.fetch.listen(function (organizationId) {
    $.ajax({
            url: 'someurl'
            headers: {
                'Authorization': profileStore.getAuthToken()
            }
        })
});

```

Are there any solutions to solving this?

**Comment by spoike** [comment]
Circular references is usually an indication that you're not doing it flux-y since the data should flow unidirectionally. Here are some pointers:

1. Stop using setters and getters. Stores are not an implementation of the Repository pattern and having them is very FRP-y either. If some reference needs it, then you're probably not passing all the data in the store through `trigger`.
2. Stores should be doing one thing well (Single Responsibility Principle). The `profileStore.getAuthToken` aside from being a getter (see point 1), is also an indication that `profileStore` is doing more than what is needed. Why not putting that in an `authTokenStore` instead?
3. Everything does not need to be a store so why not make the auth token retrieval a simple module? And if you want to be real fancy: have the module return a promise?

Hope this helps.

**Comment by brianlawasdf123** [comment]
That does help, thanks.

**Comment by unclecheese** [comment]
This really helped me, too. Great write up, @spoike ..
