### ISSUE TITLE
customize the name used for the "on"* store methods.

### ISSUE THREAD

**Issue by dmwyatt** [spoike/refluxjs#354]
I'd like to be able to name my methods something other than `onSomeAction`.  

I guess this would require the ability to provide a custom `callbackname` function or maybe allow a configurable regex for parsing these.

To my mind these are private methods and thus for our code style they should be prefixed with an underscore.

**Comment by LongLiveCHIEF** [comment]
:+1:

**Comment by clintwood** [comment]
+1, @LongLiveCHIEF, @dmwyatt, our code style for private methods is to prefix with an `_`, however, my gut says that the callback name should not deviate from the action name since this becomes a maintenance nightmare.  Perhaps a custom prefix with a default of `on` which can be set at some outer scope like `Reflux.callbackPrefix = '_on'`.

**Comment by LongLiveCHIEF** [comment]
I'm going to wait to answer this one until we've laid down a bit more of the concepts we're discussing for the internal structure of the 0.3.0 updates.  I can say that this "issue" will likely wind up being mitigated altogether by implementing es6 and even some asynchronous concepts at the core of reflux, and making the reflux things you subscribe to iterable or Observable.  In that case you'd do something like:

```js
var StoreChanges = MyStoreObject.subscribe();

StoreChanges.forEach();
```

For some good info on how that might look in your app, see: http://www.html5rocks.com/en/tutorials/es7/observe/

**Comment by clintwood** [comment]
+1 for going ES6+,  Looks like 3.0 will be a departure from 2.x... Again, looking forward to this...
