### ISSUE TITLE
Child Actions and Error Handling

### ISSUE THREAD

**Issue by AidanNichol** [spoike/refluxjs#359]
I'm struggling to get my async actions, using child actions, to work the way I think they should. Here is a simplified version of my action
```javascript
var TestAction = Reflux.createAction({
  asyncResult: true, actionName: 'TestAction', 
  preEmit: (...args)=>console.log('Emit', TestAction.actionName, ...args)
});
TestAction.listenAndPromise(function(who) {
    return db.get(who).then(function(doc) { return mem;}).catch(TestAction.failed);
  });
```
The first thing is that preEmit is being invoked for the main action but not for the child actions. I've just upgraded to the latest version from 2.5? and I'm sure it was being called then.

If I omit the catch clause then I get an uncaught error in a promise warning logged to the console and the **TestActionFailed** action is dispatched. That's sort of OK. The actions are dispatching as expected but I don't want the log polluted with errors that are really being handled via the failed action.

Having the catch clause suppresses the warning and the **TestActionFailed** is dispatched - great. But the **TestActionCompleted** is also dispatched with no payload. Isn't this an error. Promises alway invoke the resolve or the reject functions but never both. Given that the child actions are controlled by the promise shouldn't the same hold here i.e. one, and only one, of them will get dispatched.

**Comment by VanTanev** [comment]
@AidanNichol What you probably want is:
```
TestAction.listenAndPromise(db.get)
```

This will invoke `db.get` with the params to `TestAction`, and then trigger `TestAction.completed/failed` based on the result of the promise returned from `db.get`.

For what you're doing, (manually calling `TestAction.completed/failed`), you should just use `TestAction.listen`.

And one more thing: you wanna set `TestAction` to be sync, because of https://github.com/spoike/refluxjs/issues/296. :)

**Comment by LongLiveCHIEF** [comment]
> Promises alway invoke the resolve or the reject functions but never both.

Promises don't invoke either method, whatever object is executing the promise takes care of that. It sounds like semantics, but understanding the difference is probably the biggest gotcha for trying to grapple with promises.

>Given that the child actions are controlled by the promise shouldn't the same hold here i.e. one, and only one, of them will get dispatched.

This is related to the comment I made above, in that promises don't invoke themselves, leaving that up to the calling object. From there, you can see that the child actions are indirectly invoked by the action handler, and therefore how they're dispatched is completely up to you to handle once the initial promise has resolved/rejected. 

Also keep in mind, that "completed" and "failed" are only *the most common* examples of child actions. Since they're the most common, reflux gives you some special handling for those methods. You are free to create any and as many child actions you want, and dispatch them however you wish.
