### ISSUE TITLE
Store action trigger and/or Reflux.listenTo appear to be broken

### ISSUE THREAD

**Issue by thetiby** [spoike/refluxjs#360]
Hi there. This is either a big bug or I'm having trouble understanding the usefulness of having **different view (React) handlers** for different actions triggered by the store if **all** handlers are being called **for each of those actions**.

Here's what I mean: https://jsfiddle.net/69z2wepo/10946/

Expected output:
```
action 1 handler triggered from action 1
-----------------
action 2 handler triggered from action 2
```
What I actually get:
```
action 1 handler triggered from action 1
action 2 handler triggered from action 1
-----------------
action 1 handler triggered from action 2
action 2 handler triggered from action 2
```

Just by looking at this output I can say this is wrong. But to clarify: action 1 should only trigger the handler for action 1 and action 2 should only trigger the handler for action 2.

Am I doing something wrong?

Please help! 

cc @spoike 

P.S: I also tried manually using `ComponentDidMount` with `this.listenTo`; same behaviour.

**Comment by thetiby** [comment]
Hope this helps you fix the bug when you read this issue but unfortunately I must swap out refluxjs from my project..looks like I'll be back to doing switches for the action name after all...

**Comment by spoike** [comment]
Stores only sends off an update event, each time `trigger(...)` is called. This is by design since stores are supposed to be handling data and pass that on to the components. Components aren't supposed to know about flux actions other than to invoke them, only the data that gets mutated by the actions.

If you really need a component to react to actions you could do a short-cut of not using a store and let the component listen to the actions directly instead. Like this:

```jsx
Status = React.createClass({
    mixins: [
        Reflux.listenTo(actions.action1,"onAction1"),
        Reflux.listenTo(actions.action2,"onAction2")
    ],
    onAction1: function() {
        console.log("action 1 handler");
        setTimeout(actions.action2, 1000);
    },
    onAction2: function(specific_action_param) {
        console.log("action 2 handler");
    },
    render: function() {
        return (<div onClick={actions.action1}> lorem ipsum </div>);
    }
});
```

@thetiby Is there some particular reason you want to pass on action events to a component through a store?

**Comment by thetiby** [comment]
I actually ended up doing exactly that - although now the flow it's a bit odd because I have these actions that have the sole purpose of mutating data and then calling other actions so that the components can react. (therefore bypassing the "trigger" functionality altogether, since it does something really strange)

Normally, I would've tought that the flow: Action1 -> Store.onAction1 -> Component.onAction1 wouldn't have any effect on a different flow of action, given by Action2 -> Store.onAction2 -> Component.onAction2.

My question is: how is it by design to register different handlers in the component if they all react to the store trigger, regardless which action did that trigger? Specifically, what's the purpose of having
```
this.listenTo(Store, "onAction1");
this.listenTo(Store, "onAction2");
this.listenTo(Store, "onAction3");
```
 if any of the 3 actions will trigger **all** the above handlers in the component?

Also, for your last question: my purpose is simple! The store has the data, and 1 of my components only knows part of the data (let's say, an ID). That component calls`actions.action1(id)`, the store handles this by getting the required data for the other component which has the `onAction1(requiredDataWhichTheStoreSent)` handler, which it can go on and render. However, I don't have a single action. I also have `actions.action2(some_other_component1_limited_data)` that needs to pass onto the store for it to provide the actual needed data in the component2. 

So I want component2 to listen to this single store and react differently according to the action that was triggered (from the other component) and handled by the store (since that's where the data for this component is). 

Registering specific handlers like that *appears* to do just this. The behaviour that actually happens seems very misleading and weird, because one could see it actually behaving like: `this.listenTo(Store)`(not sure if this actually exists in your lib), where any actions handled by the store will trigger *ALL* handlers in the component listening on the **entire** store (as opposed to listening for specific action callbacks of the store, like the syntax suggests now). 

You said that:

> Components aren't supposed to know about flux actions other than to invoke them, only the data that gets mutated by the actions.

I would think that doing `mixins: [Reflux.listenTo(someStore,"onSomeAction")]` implies that the component knows about the `someAction` action, and expects the store to send it the actual needed data in response to that action. With only 1 action, in really does this, but if we add another one: `mixins: [Reflux.listenTo(someStore,"onSomeAction"), Reflux.listenTo(someStore,"onSomeOtherAction)]`, the component will trigger both handlers **regardless** of which action the store handled.

I probably wrote the same thing 3 times in slightly different matters, but are you really sure that this is intended behaviour and not a bug?

**Comment by spoike** [comment]
If your component is listening to the store then it is not the action that does the triggering, it is the store that does that. In your example you may think writing "onSomeAction" will imply that, but that's not what happens under the hood.

As the example is wired the flow is actually like this: 

```
Action1 -> Store.onAction1 -+-> Component.onAction1
                            |
                            +-> Component.onAction2

Action2 -> Store.onAction2 -+-> Component.onAction1
                            |
                            +-> Component.onAction2
```

On the component it makes more sense to write `Reflux.listenTo(someStore, "onSomeStoreHasUpdated")` because that is what is happening.

So what you really want to be doing is this:

```
Action 1 -> Store.onAction1 --+
                              |
                              +--> Component.onStoreUpdate
                              |
Action 2 -> Store.onAction2 --+
```

If you're really adamant on passing on what action has been called you could pass that on as data in the `onActionX` handlers:

```javascript
onAction1: function() {
    // handle this.data
    // or something...
    trigger({
        data: this.data
        originator: "action1" // or actions.action1 if you want to pass on the object itself
    });
},
onAction2: function() {
    // handle this.data
    // or something...
    trigger({
        data: this.data
        originator: "action2" // or actions.action2 if you want to pass on the object itself
    });
}
```

**Comment by thetiby** [comment]
Can you please add this [to the docs](https://github.com/spoike/refluxjs#using-refluxlistento)? 

I really thought that a component was listening to the `Store.onSomeAction` and not to the whole store itself (thinking that this is one of the additions of Reflux). Now that I undertand this I get that the only real usage of multiple calls to `listenTo` of a component is when listening to multiple stores. (or actions, as that is possible as well)

**Comment by daddybh** [comment]
hi @spoike , Are you considering adding support for listening multiple actions within a component ?

Because, when I build app with reflux. I have some confusion of the relationship between component and store.
For example, I have a `SettingStore` which manipulate a settings object. When component mount, load setting data from server and sync back to server after some modifications. 

So I have a store like:

```
var setting = {};
var loaded = false;
module.exports = Reflux.createStore({
    listenables : SettingAction,
    loadSetting: function(){
        if(loaded){
            return this.updateSetting();
        }
        $.get('/getSetting', function(resp){
            if(resp.status.code === 0){
                loaded = true;
                this.updateSetting(resp.data);
            }
        }.bind(this));
    },
    saveSetting: function(){
        $.post('/setSetting', function(resp){
            if(resp.status.code === 0){
                //here I want to notify component to popup a success info
            }
        }.bind(this));
    },
    updateSetting: function(resp){
        if(resp){
            setting = resp;
        }
        this.trigger(setting);
    }
});
```
I can use the workaround you mentioned above. But there would be some `if-else` within the callback of component. And this callback should not call `onSettingUpdate` anymore.

In my opinion, If I trigger something in a method of a store, it would be ideal to call the same method in component or something like `onUpdateSetting/onSaveSetting`  

So what's your suggest about this circumstance? And thanks for your great work.

**Comment by spoike** [comment]
@daddybh You could create a `UpdatedSettingsStore` that listens to your `SettingStore` and does the `if-else`and let the component listen to that store instead.

**Comment by daddybh** [comment]
thank you @spoike, for now, I think it is better to do it in you way.
