### ISSUE TITLE
Required / Arg Checking on Actions

### ISSUE THREAD

**Issue by kortina** [spoike/refluxjs#364]
Have you ever considered added some safety to actions, eg something like the following?

```
var Actions = Reflux.createActions({
    walk: {required: true},
    run: {args: ['speed:Number']}
  });

var ActionResponder = React.createClass({
    getInitialState: function() { },
    onRun: function() {
        console.log("running");
    },
    componentDidMount: function() {
        this.listenToMany(Actions);
    }
});
```

Might raise 2 errors:

* did not implement required listener `onWalk`
* listener `onRun` accepts incorrect number of arguments, should accept 1 argument, `speed:Number`

This is just a sketch, not a suggestion for the actual interface, but wanted to see if you had thought about anything like this. It might save people from making some silly implementation mistakes.

**Comment by spoike** [comment]
I did think about it a long time ago however there are matcher libs out already such as [jshamcrest](http://danielmartins.ninja/jshamcrest/uses.html#object-filtering) that can be used in [`shouldEmit` action hook](https://github.com/spoike/refluxjs#action-hooks).

Since I want the core library to be very lightweight with as small api surface as possible I have to cut that feature out. I am however open to extensions to reflux as seperate projects and npm libs.
