### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by iofjuupasli** [spoike/refluxjs#378]
Do you think that reflux still very unstable and not usable? So you wouldn't recomend it for anyone to use?

If not, I think it's time for v1.

[We fail to follow SemVer – and why it needn’t matter by Stephan Bönnemann at JSConf Budapest 2015](https://www.youtube.com/watch?v=tc2UgG5L7WM)

**Comment by LongLiveCHIEF** [comment]
**Section 4 of the semver standard:**

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Is Reflux useable? Yes, very much so. Would I say it's stable? That doesn't really have anything to do with v1. Stability is relative to the minor number of semver. I'm all for going to v1 as soon as it's possible, but that number should be turned when the owner and maintainers have decided they can or will be able to achieve what the package is meant to accomplish, without requiring any significant alterations to the api.

The 0.2 branch in and of itself is fairly stable, but it's got some kinks and updates to work out. On other fronts, we're bringing new features to Reflux, and we can already see a few places where the public API will either have methods removed or added, and in such a way that they affect usage of the public methods that remained unaltered. 

I think that definitively answers the question of reflux stability in the sense and spirit of the major semver number specification and node implementation. We haven't yet reached that point. 

The speaker is half right in his talk. Yes, there are a lot of packages out there that should be 1.0 or greater. A *lot* of packages. That doesn't mean though that you should start your development off with 1.0 and build from there. The node/NPM semver api handles the `0.Y.Z` differently* than every major semver tag `1.X` or greater, being more strict with calculating outdated/compatible in regards to version numbers.  This is because during early development of software, developers require the flexibility to make significant alterations to their public api, without having to be bogged down by supporting both the old and new via 1.X deprecation handling expectations.

*(at least it did until 2.14 was released, which I believe has some changes to how major versions dependencies behave)
